### ISSUE TITLE
Please define the license, like MIT, Apache...

### ISSUE THREAD

**Issue by GermanBluefox** [bobaos/bobaos#1]

**Comment by GermanBluefox** [comment]
I could find ISC in the package.json.
Can you add https://github.com/nevir/readable-licenses/blob/master/markdown/ISC-LICENSE.md
as "LICENSE" file into your project?

Thank you.

**Comment by shabunin** [comment]
Will add licensing in next versions. Now you can use with ISC conditions in according to package.json file.

Thank you.

**Comment by GermanBluefox** [comment]
BTW: Do you know about ioBroker Project?
How do you control and visualize your home? It is written completely with node.js (ca 1.8 Million lines of code)

**Comment by shabunin** [comment]
Looks a bit similar to node-red. You may write me to va.shabunin at physics.msu.ru to avoid offtopic in this issue thread.

**Comment by shabunin** [comment]
done. Now using DBAD licensing
